"""Build a self-contained WebGL studio. Python standard library only."""
from pathlib import Path
import argparse
import json
import shutil
import re

ROOT = Path(__file__).resolve().parents[1]
SHADERS = ROOT / "src/shaders"
WEB = ROOT / "src/web"


def read(path):
    return path.read_text(encoding="utf-8")


def shader_source(filename, stack=()):
    """Resolve local GLSL includes without a runtime loader or network requests."""
    if filename in stack:
        raise ValueError(f"Cyclic shader include: {stack + (filename,)}")
    source = read(SHADERS / filename)
    return re.sub(
        r'^#include "([A-Za-z0-9_.-]+)"$',
        lambda match: shader_source(match[1], stack + (filename,)),
        source,
        flags=re.MULTILINE,
    )


def build():
    core = read(SHADERS / "FractalHatching.glsl") + "\n" + read(SHADERS / "PencilHatching.glsl")
    scene = shader_source("scene.frag").replace("// CORE_INSERT", core)
    composite = read(SHADERS / "outline-composite.frag").replace("// CORE_INSERT", core)
    composite = composite.replace("// OUTLINE_CORE_INSERT", read(SHADERS / "PencilOutline.glsl"))
    city_sources = {
        name: shader_source(filename)
        for name, filename in {
            "vertex": "city.vert",
            "shadowVertex": "city-shadow.vert",
            "depth": "depth-only.frag",
            "fill": "city-fill.frag",
            "raw": "city-raw.frag",
            "metadata": "city-metadata.frag",
            "fullscreen": "fullscreen.vert",
        }.items()
    }
    modules = "const CITY_SHADERS = " + json.dumps(city_sources) + ";"
    javascript = "\n".join([read(WEB / "city-geometry.js"), modules, read(WEB / "city-renderer.js"), read(WEB / "first-person.js"), read(WEB / "demo.js")])
    fragment = read(WEB / "studio.html")
    for token, value in {
        "SHADER_INSERT": scene,
        "PENCIL_CORE_TEXT": core,
        "EDGE_PASS_TEXT": read(SHADERS / "outline-edge.frag"),
        "COMPOSITE_PASS_TEXT": composite,
        "JS_INSERT": javascript,
    }.items():
        assert fragment.count(token) == 1, token
        fragment = fragment.replace(token, value)
    return """<!doctype html>
<!-- Generated by scripts/build.py. Edit src/ files, then rebuild. -->
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="Try fractal pencil hatching and screen-space outlines on 3D scenes.">
<title>Sketchy: pencil shading demo</title><style>""" + read(WEB / "studio.css") + """</style></head>
<body><header><div><a href="index.html" class="wordmark">Sketchy</a><span class="subtitle">Pencil shading for 3D scenes</span></div>
<nav aria-label="Project"><a href="https://github.com/otdavies/sketchy#how-it-works">How it works</a><a href="https://github.com/otdavies/sketchy">Source</a></nav></header>
<main>""" + fragment + """</main>
<footer><span data-navigation-hint>Drag to orbit. Scroll to zoom.</span><span><a href="gallery.html">Examples</a> · <a href="https://github.com/otdavies/sketchy/blob/main/docs/references.md">References</a></span></footer>
</body></html>
"""



if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the committed demo is stale")
    parser.add_argument("--site", type=Path, help="Stage the GitHub Pages files in this directory")
    args = parser.parse_args()
    target = ROOT / "demos/index.html"
    output = build()
    if args.check:
        if not target.exists() or read(target) != output:
            raise SystemExit("Demo is stale: run python scripts/build.py")
        print("Demo matches source.")
    else:
        target.write_text(output, encoding="utf-8", newline="\n")
        print("Built demos/index.html")

    if args.site:
        args.site.mkdir(parents=True, exist_ok=True)
        (args.site / "index.html").write_text(output, encoding="utf-8", newline="\n")
        gallery = read(ROOT / "demos/gallery.html").replace("../docs/images/", "images/")
        (args.site / "gallery.html").write_text(gallery, encoding="utf-8", newline="\n")
        shutil.copytree(ROOT / "docs/images", args.site / "images", dirs_exist_ok=True)
        (args.site / ".nojekyll").touch()
        print(f"Staged site in {args.site}")
