"""Build a self-contained WebGL studio. Python standard library only."""
from pathlib import Path
import argparse
import json

ROOT = Path(__file__).resolve().parents[1]
SHADERS = ROOT / "src/shaders"
WEB = ROOT / "src/web"


def read(path):
    return path.read_text(encoding="utf-8")


def build():
    core = read(SHADERS / "FractalHatching.glsl") + "\n" + read(SHADERS / "PencilHatching.glsl")
    scene = read(SHADERS / "scene.frag").replace("// CORE_INSERT", core)
    composite = read(SHADERS / "outline-composite.frag").replace("// CORE_INSERT", core)
    composite = composite.replace("// OUTLINE_CORE_INSERT", read(SHADERS / "PencilOutline.glsl"))
    modules = "\n".join(
        "const " + name + "=" + json.dumps(read(SHADERS / file)) + ";"
        for name, file in [("CITY_LIGHTING_GLSL", "CityLighting.glsl"), ("CITY_SURFACE_GLSL", "CitySurface.glsl")]
    )
    javascript = "\n".join([read(WEB / "city-geometry.js"), modules, read(WEB / "city-renderer.js"), read(WEB / "demo.js")])
    fragment = read(WEB / "studio.html")
    for token, value in {
        "SHADER_INSERT": scene,
        "PENCIL_CORE_TEXT": core,
        "EDGE_PASS_TEXT": read(SHADERS / "outline-edge.frag"),
        "COMPOSITE_PASS_TEXT": composite,
        "JS_INSERT": javascript,
    }.items():
        assert fragment.count(token) == 1, token
        fragment = fragment.replace(token, value)
    return """<!doctype html>
<!-- Generated by scripts/build.py. Edit src/ files, then rebuild. -->
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sketchy — drawing studio</title><style>""" + read(WEB / "studio.css") + """</style></head>
<body><header><a href="index.html" class="wordmark">Sketchy</a><a href="https://github.com/otdavies/sketchy">Research &amp; source ↗</a></header>
<main><div class="intro"><span class="eyebrow">A study in paper and light</span><h1>A world, drawn in pencil.</h1>
<p>Surface strokes that reveal new detail as you move closer. Image-space contours with a little life in the line.</p></div>
""" + fragment + """
<details><summary>How to explore</summary><p>Drag to orbit the city or sculpture; drag to pan the flat study. Zoom reveals nested strokes. Pencil fit adds subpixel wiggle; Stable fit keeps clean contours. Lines only isolates fitting. Raw shadows and Light only separate visibility from artistic shading.</p><p>Hold drawings commits a complete image at up to 10 Hz, without blending. Zoom redraws small stroke variations; orbit, light and traffic keep their seed. Nothing boils when idle. Fast uses two pencil samples; Reference uses four. WebGL2 is required. No external assets or network calls are used by the renderer.</p></details>
</main><footer>Sketchy · Rendering research · <a href="https://github.com/otdavies/sketchy/blob/main/docs/references.md">Sources and attribution</a></footer></body></html>
"""


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the committed demo is stale")
    args = parser.parse_args()
    target = ROOT / "demos/studio.html"
    output = build()
    if args.check:
        if not target.exists() or read(target) != output:
            raise SystemExit("Demo is stale: run python scripts/build.py")
        print("Demo matches source.")
    else:
        target.write_text(output, encoding="utf-8", newline="\n")
        print("Built demos/studio.html")
