"""Translate the small shared contour kernel; --check detects adapter drift."""
import argparse
import re
from pathlib import Path

root = Path(__file__).resolve().parents[1]
source = (root / "src/shaders/PencilOutline.glsl").read_text(encoding="utf-8")
source = source.replace(
    "return texelFetch(edgeSeeds, clamp(pixel, ivec2(0), textureSize(edgeSeeds, 0) - 1), 0);",
    "uint width, height;\n    edgeSeeds.GetDimensions(width, height);\n"
    "    return edgeSeeds.Load(int3(clamp(pixel, int2(0, 0), int2(width, height) - 1), 0));",
)
source = source.replace(
    "float occupancy = textureLod(edgeSeeds, pixelPosition / resolution, 3.0).a;",
    "#ifndef PO_NO_OCCUPANCY_MIPS\n    float occupancy = edgeSeeds.SampleLevel(edgeLinearSampler, pixelPosition / resolution, 3.0).a;",
).replace("    ivec2 centerPixel = ivec2(pixelPosition);", "#endif\n    ivec2 centerPixel = ivec2(pixelPosition);")
source = source.replace("clamp(0.64 * linePressure", "clamp(PO_OUTLINE_WIDTH * linePressure")
for size in (2, 3, 4):
    source = re.sub(rf"vec{size}\(0(?:\.0)?\)", "float" + str(size) + "(" + ", ".join(["0"] * size) + ")", source)
for before, after in {"ivec2": "int2", "vec2": "float2", "vec3": "float3", "vec4": "float4", "mix": "lerp", "atan": "atan2", "mod": "poMod"}.items():
    source = re.sub(r"\b" + before + r"\b", after, source)
source = """// Generated by scripts/sync-outline-hlsl.py from src/shaders/PencilOutline.glsl.
#ifndef SCREEN_SPACE_PENCIL_OUTLINE_INCLUDED
#define SCREEN_SPACE_PENCIL_OUTLINE_INCLUDED
#ifndef PO_OUTLINE_WIDTH
#define PO_OUTLINE_WIDTH 0.64
#endif
float poMod(float value, float period) { return value - period * floor(value / period); }
""" + source + "\n#endif\n"
parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
for target in (root / "reference/hlsl/PencilOutline.hlsl", root / "Packages/com.otdavies.sketchy/Runtime/Shaders/PencilOutline.hlsl"):
    if args.check:
        assert target.read_text(encoding="utf-8") == source, f"Outline adapter is stale: {target}"
    else:
        target.write_text(source, encoding="utf-8")
print("Outline adapters match GLSL." if args.check else "Updated both HLSL outline adapters.")
